### ISSUE TITLE
Defined materials through  Rhino inside Revit 

### ISSUE THREAD

**Issue by hadas790** [PachydermAcoustic/PachydermAcoustic_Grasshopper#1]
Hey everyone
 we would like to use honeybee zones for extracting geometry from Revit and analyze it in grasshopper plug-ins . 

  since the the acoustics pachyderm require to define the materials in rhino , Is it possible to do so in the Grasshopper ?
we would like to have as much data as possible on grasshopper than inside rhino

( I'm familiar with the option to choose the layers in GL component however it still have to be adjust in rhino and we want to know if its possible to adjust martials in a different way )

thanks in advance ! 
Hadas

**Comment by AvdHarten** [comment]
Hi Hadas,
I have some things coming in my beta version, but right now I don' think that feature is available in the public version.
The way it will work, you can modify a layer's material from grasshopper component.
If you can think of a better way to do it, I can see if I can figure it out for the next release.
Arthur

**Comment by AvdHarten** [comment]
I may have spoken too soon. Look for a component called "Layer Material Properties".

Arthur
