### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by themikestrikes** [PachydermAcoustic/PachydermAcoustic_Grasshopper#2]
Hi,
i'm wondering if i missed something or there's a problem in the solution.

After the download i opened the project and noticed that a couple of files are missing.
 
![files](https://user-images.githubusercontent.com/92297573/136756154-57471f66-cf97-4d65-8d4d-542e3174c03a.PNG)

Thank You!

**Comment by AvdHarten** [comment]
Should be resolved now.
